// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"OrangeCustomEvents","status":true,"description":"This plugin Will let you add or copy events to the current map","parameters":{}},
{"name":"milkcocoa","status":true,"description":"","parameters":{}},
{"name":"MilkcocoaClient","status":true,"description":"Milkcocoaで接続します。","parameters":{"appId":"woodihoeu8hb","dataPath":"rpgmv","sendPosition":"1","useSync":"0"}},
{"name":"EnemyBook","status":true,"description":"モンスター図鑑です。敵キャラの詳細なステータスを表示します。","parameters":{"Unknown Data":"？？？？？？"}},
{"name":"ItemBook","status":true,"description":"アイテム図鑑です。アイテムの詳細なステータスを表示します。","parameters":{"Unknown Data":"？？？？？？","Price Text":"価格","Equip Text":"装備","Type Text":"タイプ"}}
];
