// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"milkcocoa","status":true,"description":"","parameters":{}},
{"name":"MilkcocoaClient","status":true,"description":"Milkcocoaで接続します。","parameters":{"appId":"woodihoeu8hb","dataPath":"rpgmv"}}
];
